---
abstract: 'Base class and script for creating Kramerius downloader.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Kramerius-To-Images
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  App::Kramerius::V4: 0
  Class::Utils: 0
  Cwd: 0
  Data::Kramerius: 0
  English: 0
  Error::Pure: 0
  File::Spec::Functions: 0
  Getopt::Std: 0
  HTTP::Request: 0
  IO::Barf: 0
  JSON::XS: 0
  LWP::UserAgent: 6
  METS::Files: 0
  Perl6::Slurp: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-Kramerius-To-Images/issues
  homepage: https://github.com/michal-josef-spacek/App-Kramerius-To-Images
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Kramerius-To-Images
version: '0.04'
